name: Code Format Check

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  code-format-check:
    name: Code Format Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
        golangci-lint --version

    - name: Check code format
      run: |
        golangci-lint run --fast --fix
